### ISSUE TITLE
How to inference InternVL-14B-224px on multiple GPUs?

### ISSUE THREAD

**Issue by bluemandora** [OpenGVLab/InternVL#42]
My GPU is A30(24G)，cannot load the model on single GPU. I tried to load the huggingface model with `device_map='auto'`, it report the error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/work/.conda/envs/xxx/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 561, in from_pretrained
    return model_class.from_pretrained(
  File "/home/work/.conda/envs/xxx/lib/python3.8/site-packages/transformers/modeling_utils.py", line 3606, in from_pretrained
    no_split_modules = model._get_no_split_modules(device_map)
  File "/home/work/.conda/envs/xxx/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1690, in _get_no_split_modules
    raise ValueError(
ValueError: InternVisionModel does not support `device_map='auto'`. To implement support, the model class needs to implement the `_no_split_modules` attribute.
```

here is my code:
```
import torch
from transformers import AutoModel, CLIPImageProcessor
model = AutoModel.from_pretrained(
    'OpenGVLab/InternVL-14B-224px',
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage=True,
    trust_remote_code=True,
    device_map='auto').eval()
```

**Comment by czczup** [comment]
Thanks for you feedback, I will fix this bug.

**Comment by czczup** [comment]
<img width="793" alt="image" src="https://github.com/OpenGVLab/InternVL/assets/23737120/15136384-3001-4aa0-a2f1-ae888f3ccd1a">

I just fixed this bug. The solution was indeed straightforward – I simply added _no_split_modules = ['InternAttention'] to the model's code. You should now be able to load the model on multiple GPUs.

**Comment by bluemandora** [comment]
It's still not work for me. The error:
<img width="1270" alt="image" src="https://github.com/OpenGVLab/InternVL/assets/8968651/386b836f-ab77-4aa0-965e-14a1baf2f945">


Then I changed `_no_split_modules = ['InternAttention']` to `_no_split_modules = ['InternVisionEncoderLayer']`. Problem solved.

**Comment by czczup** [comment]
Thanks.
